/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Santiago Pérez
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        itemUsuarios = new javax.swing.JMenuItem();
        ItemRoles = new javax.swing.JMenuItem();
        ItemSede = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        ItemContabilidad = new javax.swing.JMenuItem();
        ItemTrabajos = new javax.swing.JMenuItem();
        ItemTMantenimiento = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ItemProveedores = new javax.swing.JMenuItem();
        ItemPeticiones = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemEmpleados = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MYBICI");

        btnSalir.setText("Salir");

        jMenu5.setText("Adiministración");

        itemUsuarios.setText("Usuarios");
        jMenu5.add(itemUsuarios);

        ItemRoles.setText("Roles");
        jMenu5.add(ItemRoles);

        ItemSede.setText("Sede");
        jMenu5.add(ItemSede);

        jMenuBar1.add(jMenu5);

        jMenu1.setText("Sede");

        ItemContabilidad.setText("Contabilidad");
        jMenu1.add(ItemContabilidad);

        ItemTrabajos.setText("Trabajos");
        jMenu1.add(ItemTrabajos);

        ItemTMantenimiento.setText("Mantenimiento Taller");
        jMenu1.add(ItemTMantenimiento);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Inventario");

        ItemProveedores.setText("Proveedores");
        jMenu2.add(ItemProveedores);

        ItemPeticiones.setText("Peticiones");
        jMenu2.add(ItemPeticiones);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Empleados");

        itemEmpleados.setText("Empleados");
        jMenu3.add(itemEmpleados);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(318, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(308, 308, 308))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addGap(106, 106, 106))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 338, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(77, 77, 77))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem ItemContabilidad;
    public javax.swing.JMenuItem ItemPeticiones;
    public javax.swing.JMenuItem ItemProveedores;
    public javax.swing.JMenuItem ItemRoles;
    public javax.swing.JMenuItem ItemSede;
    public javax.swing.JMenuItem ItemTMantenimiento;
    public javax.swing.JMenuItem ItemTrabajos;
    public javax.swing.JButton btnSalir;
    public javax.swing.JMenuItem itemEmpleados;
    public javax.swing.JMenuItem itemUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    public javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
