/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Santiago Pérez
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAdministracion = new javax.swing.JMenu();
        itemUsuarios = new javax.swing.JMenuItem();
        ItemRoles = new javax.swing.JMenuItem();
        ItemSede = new javax.swing.JMenuItem();
        menuSede = new javax.swing.JMenu();
        ItemContabilidad = new javax.swing.JMenuItem();
        ItemTrabajos = new javax.swing.JMenuItem();
        ItemTMantenimiento = new javax.swing.JMenuItem();
        itemFacturacion = new javax.swing.JMenuItem();
        menuInventario = new javax.swing.JMenu();
        ItemProveedores = new javax.swing.JMenuItem();
        ItemPeticiones = new javax.swing.JMenuItem();
        menuEmpleados = new javax.swing.JMenu();
        itemEmpleados = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenu();
        itemClientes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel1.setText("BICI BIKES");

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSalir.setText("Salir");

        lblUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblUsuario.setText("Usuario:");

        lblRol.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblRol.setText("Rol: ");

        menuAdministracion.setText("Adiministración");

        itemUsuarios.setText("Usuarios");
        menuAdministracion.add(itemUsuarios);

        ItemRoles.setText("Roles");
        menuAdministracion.add(ItemRoles);

        ItemSede.setText("Sede");
        menuAdministracion.add(ItemSede);

        jMenuBar1.add(menuAdministracion);

        menuSede.setText("Sede");

        ItemContabilidad.setText("Contabilidad");
        menuSede.add(ItemContabilidad);

        ItemTrabajos.setText("Trabajos");
        menuSede.add(ItemTrabajos);

        ItemTMantenimiento.setText("Mantenimiento Taller");
        menuSede.add(ItemTMantenimiento);

        itemFacturacion.setText("Facturacón");
        menuSede.add(itemFacturacion);

        jMenuBar1.add(menuSede);

        menuInventario.setText("Inventario");

        ItemProveedores.setText("Proveedores");
        menuInventario.add(ItemProveedores);

        ItemPeticiones.setText("Peticiones");
        menuInventario.add(ItemPeticiones);

        jMenuBar1.add(menuInventario);

        menuEmpleados.setText("Empleados");

        itemEmpleados.setText("Empleados");
        menuEmpleados.add(itemEmpleados);

        jMenuBar1.add(menuEmpleados);

        menuClientes.setText("Clientes");

        itemClientes.setText("Clientes");
        menuClientes.add(itemClientes);

        jMenuBar1.add(menuClientes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario)
                    .addComponent(lblRol)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(157, 157, 157))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(btnSalir))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem ItemContabilidad;
    public javax.swing.JMenuItem ItemPeticiones;
    public javax.swing.JMenuItem ItemProveedores;
    public javax.swing.JMenuItem ItemRoles;
    public javax.swing.JMenuItem ItemSede;
    public javax.swing.JMenuItem ItemTMantenimiento;
    public javax.swing.JMenuItem ItemTrabajos;
    public javax.swing.JButton btnSalir;
    public javax.swing.JMenuItem itemClientes;
    public javax.swing.JMenuItem itemEmpleados;
    public javax.swing.JMenuItem itemFacturacion;
    public javax.swing.JMenuItem itemUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JLabel lblRol;
    public javax.swing.JLabel lblUsuario;
    public javax.swing.JMenu menuAdministracion;
    private javax.swing.JMenu menuClientes;
    public javax.swing.JMenu menuEmpleados;
    public javax.swing.JMenu menuInventario;
    public javax.swing.JMenu menuSede;
    // End of variables declaration//GEN-END:variables
}
