/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author F. PLAZA
 */
public class VistaFacturacion extends javax.swing.JFrame {

    /**
     * Creates new form VistaFactuacion
     */
    public VistaFacturacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIDFactura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCCEmpleado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCCCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFechaVenta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTotalVenta = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFacturas = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtCodigoArticulo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtCantidadComprar = new javax.swing.JTextField();
        btnBuscarFactura = new javax.swing.JToggleButton();
        btnCarrito = new javax.swing.JToggleButton();
        btnBuscarInventario = new javax.swing.JToggleButton();
        jLabel13 = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        btnSacarCarrito = new javax.swing.JToggleButton();
        jLabel14 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblArticulos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtIVA = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnlimpiarArt = new javax.swing.JToggleButton();
        btnArtFact = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Información de Factura");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 170, -1));

        jLabel2.setText("Código de la Factura");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 170, -1));
        getContentPane().add(txtIDFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 165, -1));

        jLabel3.setText("C.C. Empleado");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 160, -1));
        getContentPane().add(txtCCEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 165, -1));

        jLabel4.setText("C.C. Cliente");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 160, -1));
        getContentPane().add(txtCCCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 165, -1));

        jLabel5.setText("Fecha Venta");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, 150, -1));

        jLabel6.setText("IVA $");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 140, -1));

        txtFechaVenta.setEditable(false);
        getContentPane().add(txtFechaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 170, -1));

        jLabel8.setText("Total Venta $");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 170, 20));

        txtTotalVenta.setEditable(false);
        getContentPane().add(txtTotalVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, 170, -1));

        btnInsertar.setText("Registrar Factura");
        getContentPane().add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, 170, -1));

        btnConsultar.setText("Consultar");
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 170, -1));

        btnListar.setText("Ver todas las facturas");
        getContentPane().add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, 170, -1));

        tblFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Factura", "CC Empleado", "CC Cliente", "Fecha Venta", "IVA", "Total Vental"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFacturas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 650, 160));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 20));

        btnLimpiar.setText("Limpiar Factura");
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, 170, -1));
        getContentPane().add(txtCodigoArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 120, 20));

        jLabel10.setText("Cantidad a Comprar");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 120, 20));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Articulos a Facturar");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 160, 20));

        jLabel12.setText("Codigo del Articulo");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 120, 20));
        getContentPane().add(txtCantidadComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 120, 20));

        btnBuscarFactura.setText("Factura");
        getContentPane().add(btnBuscarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 120, 20));

        btnCarrito.setText("Añadir al Carrito");
        getContentPane().add(btnCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 120, 20));

        btnBuscarInventario.setText("Inventario");
        getContentPane().add(btnBuscarInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 120, 20));

        jLabel13.setText("Nombre");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 120, 20));

        txtNombreProducto.setEditable(false);
        getContentPane().add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 120, 20));

        btnSacarCarrito.setText("Sacar del Carrito");
        btnSacarCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarCarritoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSacarCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 120, 20));

        jLabel14.setText("Stock");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 120, 20));

        txtStock.setEditable(false);
        getContentPane().add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 120, 20));

        tblArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Articulo", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblArticulos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 380, 140));

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel7.setText("BICI BIKES - Facturación");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        txtIVA.setEditable(false);
        getContentPane().add(txtIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, 170, -1));

        jLabel9.setText("Buscar en:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 120, 20));

        btnlimpiarArt.setText("Limpiar Articulos");
        getContentPane().add(btnlimpiarArt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 170, -1));

        btnArtFact.setText("Listar Articulos de Factura Registrada ");
        btnArtFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArtFactActionPerformed(evt);
            }
        });
        getContentPane().add(btnArtFact, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 380, -1));
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 590, 40, 20));

        btnNuevo.setText("Nuevo ");
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 110, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
      
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnSacarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarCarritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSacarCarritoActionPerformed

    private void btnArtFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArtFactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnArtFactActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnArtFact;
    public javax.swing.JToggleButton btnBuscarFactura;
    public javax.swing.JToggleButton btnBuscarInventario;
    public javax.swing.JToggleButton btnCarrito;
    public javax.swing.JButton btnConsultar;
    public javax.swing.JButton btnInsertar;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnListar;
    public javax.swing.JToggleButton btnNuevo;
    public javax.swing.JButton btnRegresar;
    public javax.swing.JToggleButton btnSacarCarrito;
    public javax.swing.JToggleButton btnlimpiarArt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tblArticulos;
    public javax.swing.JTable tblFacturas;
    public javax.swing.JTextField txtCCCliente;
    public javax.swing.JTextField txtCCEmpleado;
    public javax.swing.JTextField txtCantidadComprar;
    public javax.swing.JTextField txtCodigoArticulo;
    public javax.swing.JTextField txtFechaVenta;
    public javax.swing.JTextField txtIDFactura;
    public javax.swing.JTextField txtIVA;
    public javax.swing.JTextField txtNombreProducto;
    public javax.swing.JTextField txtStock;
    public javax.swing.JTextField txtTotalVenta;
    // End of variables declaration//GEN-END:variables
}
